-- MySQL Script generated by MySQL Workbench
-- 11/03/21 10:02:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema h8
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema h8
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `h8` DEFAULT CHARACTER SET latin1 ;
USE `h8` ;

-- -----------------------------------------------------
-- Table `h8`.`clube`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `h8`.`clube` (
  `id` INT(11) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(35) NOT NULL,
  `email` VARCHAR(35) NULL DEFAULT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  `fax` VARCHAR(15) NULL DEFAULT NULL,
  `imagem` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `h8`.`jogador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `h8`.`jogador` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
